# Generated by Django 2.1 on 2018-08-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
